import { FullLectureData } from '../src/types/index.js';

export const PRESET_LECTURES: Record<string, FullLectureData> = {
  'anatomy-circulatory-system': {
    lecture: {
      id: 'anatomy-circulatory-system',
      title: 'Human Anatomy & Circulatory Dynamics',
      subject: 'Medicine',
      summary:
        'A comprehensive university lecture examining the anatomical structure of the human heart, the dual circulatory circuits (pulmonary and systemic), ventricular mechanics, heart valves, and the electrical conduction that sustains cardiac output.',
      estimatedDuration: '4 min lesson',
      originalFileName: 'Anatomy_Lecture_3_Circulatory_Dynamics.pdf',
      fileSize: '3.4 MB',
      pageCount: 28,
      learningObjectives: [
        'Differentiate between systemic and pulmonary circulatory circuits.',
        'Trace the precise pathway of blood flow through the four cardiac chambers and primary valves.',
        'Analyze the mechanical events of ventricular systole and diastole.',
        'Explain how the sinoatrial (SA) node coordinates myocardial contraction.',
      ],
      keyTerms: [
        { term: 'Systemic Circuit', definition: 'The vascular pathway carrying oxygenated blood from the left ventricle through the aorta to body tissues, returning deoxygenated blood via the venae cavae.' },
        { term: 'Pulmonary Circuit', definition: 'The vascular loop moving deoxygenated blood from the right ventricle into the lungs for gas exchange, returning oxygenated blood to the left atrium.' },
        { term: 'Atrioventricular (AV) Valves', definition: 'Tricuspid and Mitral (bicuspid) valves that prevent backflow of blood from ventricles into atria during ventricular contraction.' },
        { term: 'Semilunar Valves', definition: 'Aortic and Pulmonary valves located at the bases of major arterial trunks that prevent retrograde flow during ventricular diastole.' },
        { term: 'Cardiac Output', definition: 'The volume of blood pumped per ventricle per minute, calculated as Stroke Volume multiplied by Heart Rate (CO = SV × HR).' },
      ],
      formulas: [
        {
          name: 'Cardiac Output (CO)',
          formula: 'CO = SV × HR',
          explanation: 'Calculates the volume of blood pumped by the left ventricle per minute.',
          variables: [
            { symbol: 'CO', label: 'Cardiac Output (L/min)' },
            { symbol: 'SV', label: 'Stroke Volume (mL/beat)' },
            { symbol: 'HR', label: 'Heart Rate (beats/min)' },
          ],
        },
        {
          name: 'Mean Arterial Pressure (MAP)',
          formula: 'MAP = DP + 1/3 (SP - DP)',
          explanation: 'Estimated average pressure in arteries throughout one cardiac cycle.',
          variables: [
            { symbol: 'DP', label: 'Diastolic Blood Pressure (mmHg)' },
            { symbol: 'SP', label: 'Systolic Blood Pressure (mmHg)' },
          ],
        },
      ],
      topics: [
        {
          id: 'cardiac-anatomy',
          title: 'The Four-Chambered Pump Architecture',
          summary: 'The heart operates as a synchronized dual-pump system with two superior receiving atria and two inferior muscular ventricles.',
          concepts: [
            {
              id: 'c1',
              name: 'Right Heart (Deoxygenated Circulation)',
              explanation: 'Receives venous return with depleted oxygen from the superior and inferior vena cava into the right atrium, pushing it into the right ventricle through the tricuspid valve.',
              importantFacts: ['Right ventricular wall is thinner (3-5mm) because pulmonary vascular resistance is low.'],
              terms: ['Right Atrium', 'Right Ventricle', 'Tricuspid Valve', 'Pulmonary Trunk'],
              examples: ['Pulmonary hypertension causes right ventricular hypertrophy due to increased workload.'],
              visualIdeas: ['Blue particle stream entering right atrium and right ventricle, then ejecting up pulmonary artery.'],
            },
            {
              id: 'c2',
              name: 'Left Heart (Oxygenated High-Pressure Pump)',
              explanation: 'Collects newly oxygenated blood from the pulmonary veins into the left atrium, passing through the bicuspid/mitral valve into the thick-walled left ventricle for high-pressure systemic ejection.',
              importantFacts: ['Left ventricular myocardium is 3x thicker than the right to overcome systemic vascular resistance (120 mmHg vs 25 mmHg).'],
              terms: ['Left Atrium', 'Left Ventricle', 'Mitral Valve', 'Aorta'],
              examples: ['Aortic stenosis narrows the outflow tract, forcing higher pressure generation.'],
              visualIdeas: ['Vivid red particle flow entering left atrium, filling left ventricle, then pulsing through the aortic arch.'],
            },
          ],
        },
        {
          id: 'cardiac-cycle',
          title: 'The Mechanical Cardiac Cycle',
          summary: 'The sequence of ventricular diastole (filling) and ventricular systole (isovolumetric contraction and rapid ejection).',
          concepts: [
            {
              id: 'c3',
              name: 'Ventricular Systole & Valve Dynamics',
              explanation: 'When ventricles contract, intraventricular pressure rises rapidly, slamming AV valves shut (First Heart Sound, S1), then opening semilunar valves when pressure exceeds aortic pressure.',
              importantFacts: ['S1 is produced by turbulent blood deceleration against closed AV valves, not the leaflets touching.'],
              terms: ['Systole', 'Isovolumetric Contraction', 'S1 Sound', 'Aortic Valve'],
              examples: ['In mitral regurgitation, backward leakage causes a pansystolic murmur.'],
              visualIdeas: ['Valves snapping shut, pressure gauge rising from 10 to 120 mmHg, ejection into aorta.'],
            },
          ],
        },
      ],
      createdAt: Date.now(),
    },
    lesson: {
      id: 'lesson-anatomy-1',
      lectureId: 'anatomy-circulatory-system',
      title: 'Visualizing Cardiac Mechanics & Dual Hemodynamics',
      summary: 'Explore the high-fidelity anatomical pump, track red and blue blood streams across circuits, and observe real-time valve dynamics.',
      totalDuration: 180,
      scenes: [
        {
          id: 'scene-1',
          order: 1,
          duration: 35,
          title: 'The Dual Pump Architecture',
          narration:
            'Welcome to the core of human hemodynamics. The heart is not a single pump, but two synchronized muscular systems operating in series. The right heart collects deoxygenated blood from the body tissues, while the left heart generates massive hydrostatic pressure to drive oxygenated blood across the systemic capillary bed.',
          visualType: 'anatomical_animation',
          visualDescription:
            'A 2D cross-section diagram of the human heart showing all four chambers with animated chamber contraction, distinct blue (deoxygenated) and red (oxygenated) flow vectors.',
          customVisualKey: 'heart_circulatory',
          elements: [
            { id: 'e1', type: 'node', label: 'Right Atrium', x: 30, y: 35, color: '#3b82f6', animation: 'pulse' },
            { id: 'e2', type: 'node', label: 'Right Ventricle', x: 35, y: 65, color: '#2563eb', animation: 'contract' },
            { id: 'e3', type: 'node', label: 'Left Atrium', x: 68, y: 35, color: '#ef4444', animation: 'pulse' },
            { id: 'e4', type: 'node', label: 'Left Ventricle', x: 65, y: 68, color: '#dc2626', animation: 'contract' },
            { id: 'e5', type: 'particle_stream', label: 'Venous Return', x: 20, y: 30, color: '#60a5fa', animation: 'flow', direction: 'down' },
            { id: 'e6', type: 'particle_stream', label: 'Aortic Ejection', x: 75, y: 20, color: '#f87171', animation: 'flow', direction: 'up' },
          ],
          labels: [
            { text: 'Deoxygenated Return (Blue)', x: 18, y: 20, highlight: false },
            { text: 'Oxygenated Ejection (Red)', x: 72, y: 15, highlight: true },
            { text: 'Interventricular Septum', x: 49, y: 60, highlight: false },
          ],
          keyTakeaway: 'The heart executes dual serial circulation: right heart for pulmonary gas exchange, left heart for systemic perfusion.',
        },
        {
          id: 'scene-2',
          order: 2,
          duration: 45,
          title: 'Blood Flow Pathway: Chamber by Chamber',
          narration:
            'Observe the strict unidirectional pathway: venous blood enters via the superior and inferior venae cavae into the right atrium, passes through the tricuspid valve into the right ventricle, and is ejected past the pulmonary semilunar valve toward the alveolar capillaries.',
          visualType: 'process_animation',
          visualDescription:
            'Step-by-step illuminated path tracing from Vena Cava -> RA -> Tricuspid -> RV -> Pulmonary Artery -> Lungs -> Pulmonary Veins -> LA -> Mitral -> LV -> Aorta.',
          customVisualKey: 'heart_circulatory',
          elements: [
            { id: 'e7', type: 'arrow', label: 'Tricuspid Gate', x: 33, y: 50, color: '#60a5fa', animation: 'flow' },
            { id: 'e8', type: 'arrow', label: 'Pulmonary Ejection', x: 42, y: 25, color: '#38bdf8', animation: 'flow' },
            { id: 'e9', type: 'pulse_zone', label: 'Alveolar Gas Exchange', x: 50, y: 10, color: '#a855f7', animation: 'pulse' },
          ],
          labels: [
            { text: '1. Right Atrium', x: 26, y: 36 },
            { text: '2. Tricuspid Valve Opens', x: 26, y: 48 },
            { text: '3. Pulmonary Artery to Lungs', x: 40, y: 18 },
          ],
          keyTakeaway: 'Unidirectional valves ensure zero retrograde leakage during cyclical pressure inversions.',
        },
        {
          id: 'scene-3',
          order: 3,
          duration: 50,
          title: 'Left Ventricular Power & Systemic Perfusion',
          narration:
            'Freshly oxygenated blood returns via the pulmonary veins into the left atrium. During ventricular diastole, the mitral valve opens, rapidly filling the left ventricle. Notice the extraordinary thickness of the left ventricular wall: it must generate over 120 millimeters of mercury of systolic pressure to overcome systemic vascular resistance and reach every capillary in the body.',
          visualType: 'anatomical_animation',
          visualDescription:
            'Close-up cutaway of the left ventricle contracting vigorously. Thick myocardium squeezes inward, mitral valve closes with tension, and the aortic valve bursts open with a bright red high-velocity stream surging into the aortic arch.',
          customVisualKey: 'heart_circulatory',
          elements: [
            { id: 'e10', type: 'box', label: 'Thick Myocardial Wall (12mm)', x: 80, y: 68, color: '#b91c1c', animation: 'contract' },
            { id: 'e11', type: 'node', label: 'Aortic Arch', x: 58, y: 14, color: '#ef4444', animation: 'pulse' },
            { id: 'e12', type: 'curve', label: 'Pressure Wave 120 mmHg', x: 65, y: 40, color: '#fbbf24', animation: 'shift_curve' },
          ],
          labels: [
            { text: 'Left Ventricle (High Pressure)', x: 68, y: 72, highlight: true },
            { text: 'Aorta (Systemic Distribution)', x: 56, y: 10, highlight: true },
          ],
          keyTakeaway: 'Left ventricular hypertrophy is an adaptive response to high systemic afterload.',
        },
        {
          id: 'scene-4',
          order: 4,
          duration: 50,
          title: 'The Cardiac Output Formula in Action',
          narration:
            'To understand whole-body hemodynamics, we turn to the fundamental governing equation: Cardiac Output equals Stroke Volume times Heart Rate. If a resting athlete has a stroke volume of 70 milliliters and a heart rate of 72 beats per minute, total output is approximately five liters every single minute—the entire circulating blood volume.',
          visualType: 'mathematical_visualization',
          visualDescription:
            'Visual formula presentation with live interactive variables: dynamic gauges for Stroke Volume (mL) and Heart Rate (BPM) multiplying into a fluid reservoir showing 5.0 Liters/min.',
          elements: [
            { id: 'e13', type: 'formula', label: 'CO = SV × HR', x: 50, y: 35, color: '#10b981', animation: 'pulse' },
            { id: 'e14', type: 'node', label: 'SV: 70 mL', x: 35, y: 60, color: '#3b82f6', animation: 'pulse' },
            { id: 'e15', type: 'node', label: 'HR: 72 BPM', x: 65, y: 60, color: '#ec4899', animation: 'pulse' },
            { id: 'e16', type: 'box', label: '5.04 L/min Total Flow', x: 50, y: 80, color: '#10b981', animation: 'expand' },
          ],
          labels: [
            { text: 'Cardiac Output Equation', x: 50, y: 22, highlight: true },
            { text: 'Resting Output ≈ 5 L/min', x: 50, y: 90 },
          ],
          keyTakeaway: 'Cardiac output adjusts dynamically during exercise via autonomic sympathetic stimulation.',
        },
      ],
    },
    quiz: {
      id: 'quiz-anatomy-1',
      lectureId: 'anatomy-circulatory-system',
      title: 'Human Anatomy & Circulatory Mechanics Mastery Exam',
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          difficulty: 'easy',
          prompt: 'Which heart chamber directly ejects deoxygenated blood into the pulmonary trunk toward the lungs?',
          options: ['Right Ventricle', 'Left Ventricle', 'Right Atrium', 'Left Atrium'],
          correctOptionIndex: 0,
          explanation: 'The right ventricle pumps deoxygenated blood through the pulmonary semilunar valve into the pulmonary trunk toward the lungs for gas exchange.',
          lectureConceptSource: 'The Four-Chambered Pump Architecture > Right Heart',
        },
        {
          id: 'q2',
          type: 'multiple_choice',
          difficulty: 'medium',
          prompt: 'Why is the myocardial wall of the left ventricle approximately three times thicker than that of the right ventricle?',
          options: [
            'It stores a larger volume of blood than the right ventricle.',
            'It must generate sufficient pressure to overcome systemic vascular resistance (120 mmHg vs 25 mmHg).',
            'It contains two tricuspid valves requiring more muscular anchor support.',
            'It contracts at double the frequency of the right ventricle.',
          ],
          correctOptionIndex: 1,
          explanation: 'The left ventricle pumps against the systemic circuit, where systemic vascular resistance demands peak systolic pressures around 120 mmHg, compared to only 25 mmHg in the low-resistance pulmonary circuit.',
          lectureConceptSource: 'The Four-Chambered Pump Architecture > Left Heart',
        },
        {
          id: 'q3',
          type: 'true_false',
          difficulty: 'easy',
          prompt: 'The pulmonary veins carry oxygen-rich blood from the lungs into the left atrium of the heart.',
          options: ['True', 'False'],
          correctOptionIndex: 0,
          explanation: 'Unlike most veins which carry deoxygenated blood, the pulmonary veins carry freshly oxygenated blood from the alveolar capillaries directly into the left atrium.',
          lectureConceptSource: 'Blood Flow Pathway & Dual Circuits',
        },
        {
          id: 'q4',
          type: 'scenario',
          difficulty: 'hard',
          prompt: 'A university athlete has a resting heart rate of 50 beats per minute and a resting cardiac output of 5.5 Liters per minute. What is the athlete\'s stroke volume?',
          options: ['110 mL/beat', '90 mL/beat', '75 mL/beat', '135 mL/beat'],
          correctOptionIndex: 0,
          explanation: 'Using the formula CO = SV × HR: 5,500 mL/min ÷ 50 beats/min = 110 mL/beat. Endurance athletes exhibit physiological cardiac hypertrophy with enhanced stroke volume.',
          lectureConceptSource: 'Cardiac Output (CO) Formula',
        },
        {
          id: 'q5',
          type: 'multiple_choice',
          difficulty: 'medium',
          prompt: 'The first heart sound ("lub" or S1) is primarily caused by which mechanical event?',
          options: [
            'Closure of the aortic and pulmonary semilunar valves at end of systole.',
            'Blood deceleration and closure of the atrioventricular (mitral and tricuspid) valves during isovolumetric ventricular contraction.',
            'The opening of the vena cava into the right atrium.',
            'The electrical depolarization wave crossing the Bundle of His.',
          ],
          correctOptionIndex: 1,
          explanation: 'S1 marks the onset of ventricular systole as rising intraventricular pressure abruptly forces the mitral and tricuspid AV valves closed.',
          lectureConceptSource: 'The Mechanical Cardiac Cycle > Ventricular Systole',
        },
      ],
    },
    games: {
      lectureId: 'anatomy-circulatory-system',
      matchConcepts: {
        title: 'Match Anatomical Structures & Roles',
        instructions: 'Pair each cardiovascular structure with its exact physiological role from the lecture.',
        pairs: [
          { id: 'mp1', term: 'Left Ventricle', definition: 'Pumps oxygenated blood into aorta at high systolic pressure' },
          { id: 'mp2', term: 'Pulmonary Artery', definition: 'Carries deoxygenated blood from right ventricle to lungs' },
          { id: 'mp3', term: 'Mitral Valve', definition: 'Prevents backflow between left atrium and left ventricle' },
          { id: 'mp4', term: 'Superior Vena Cava', definition: 'Returns deoxygenated venous blood from upper body to right atrium' },
          { id: 'mp5', term: 'Sinoatrial (SA) Node', definition: 'Primary cardiac pacemaker initiating sinus depolarization' },
        ],
      },
      memoryMatch: {
        title: 'Hemodynamic Memory Grid',
        instructions: 'Flip tiles to match cardiac terms with their physiological definition.',
        pairs: [
          { id: 'mem1', term: 'Stroke Volume', definition: 'Volume of blood ejected per beat (~70 mL)' },
          { id: 'mem2', term: 'Systole', definition: 'Phase of ventricular contraction and ejection' },
          { id: 'mem3', term: 'Diastole', definition: 'Phase of ventricular relaxation and filling' },
          { id: 'mem4', term: 'Tricuspid Valve', definition: 'Atrioventricular valve on the right side of the heart' },
          { id: 'mem5', term: 'Pulmonary Veins', definition: 'Carry oxygenated blood from lungs to left atrium' },
          { id: 'mem6', term: 'Aorta', definition: 'Largest systemic artery distributing oxygenated blood' },
        ],
      },
      rapidFire: {
        title: 'Cardiac Speed Drill',
        instructions: 'Identify the correct cardiovascular answers before the 10-second countdown runs out!',
        timePerQuestion: 10,
        questions: [
          {
            id: 'rf1',
            prompt: 'Which chamber receives venous return from the coronary sinus and venae cavae?',
            options: ['Right Atrium', 'Left Atrium', 'Right Ventricle', 'Left Ventricle'],
            correctIndex: 0,
            concept: 'Right Atrium anatomy',
          },
          {
            id: 'rf2',
            prompt: 'Is blood inside the pulmonary trunk oxygen-rich or oxygen-poor?',
            options: ['Oxygen-poor (deoxygenated)', 'Oxygen-rich (oxygenated)', 'Equal mix', 'Depends on respiration'],
            correctIndex: 0,
            concept: 'Pulmonary trunk hemodynamics',
          },
          {
            id: 'rf3',
            prompt: 'What happens to the atrioventricular valves during ventricular ejection?',
            options: ['They remain tightly closed', 'They swing wide open', 'They vibrate freely', 'They collapse outward'],
            correctIndex: 0,
            concept: 'AV valve mechanics during systole',
          },
          {
            id: 'rf4',
            prompt: 'In the formula CO = SV × HR, what does SV represent?',
            options: ['Stroke Volume', 'Systolic Velocity', 'Sinus Variance', 'Systemic Volume'],
            correctIndex: 0,
            concept: 'Cardiac Output formula',
          },
        ],
      },
      sortIt: {
        title: 'Sort the Circulatory Circuits',
        instructions: 'Classify each anatomical structure and characteristic into Pulmonary Circuit vs Systemic Circuit.',
        categories: [
          { id: 'cat-pulm', name: 'Pulmonary Circuit', description: 'Right heart & lung gas exchange loop' },
          { id: 'cat-sys', name: 'Systemic Circuit', description: 'Left heart & whole-body distribution loop' },
        ],
        items: [
          { id: 'si1', text: 'Right Ventricle', categoryId: 'cat-pulm', hint: 'Pumps blood to the pulmonary trunk' },
          { id: 'si2', text: 'Left Ventricle', categoryId: 'cat-sys', hint: 'Powers the entire systemic tree' },
          { id: 'si3', text: 'Aorta & Carotid Arteries', categoryId: 'cat-sys', hint: 'High-pressure distribution vessels' },
          { id: 'si4', text: 'Pulmonary Artery & Alveolar Bed', categoryId: 'cat-pulm', hint: 'Site of CO2/O2 exchange' },
          { id: 'si5', text: 'Superior & Inferior Venae Cavae', categoryId: 'cat-pulm', hint: 'Returns deoxygenated blood to right heart' },
          { id: 'si6', text: 'Renal & Mesenteric Capillaries', categoryId: 'cat-sys', hint: 'Supplies systemic organs' },
        ],
      },
      putItInOrder: {
        title: 'Trace Blood Flow Sequence',
        instructions: 'Arrange the sequence of blood flow beginning with deoxygenated venous return.',
        processName: 'Complete Circuit Through the Heart',
        items: [
          { id: 'ord1', stepNumber: 1, text: 'Superior/Inferior Vena Cava returns blood to Right Atrium', detail: 'Deoxygenated venous pool' },
          { id: 'ord2', stepNumber: 2, text: 'Blood passes through Tricuspid Valve into Right Ventricle', detail: 'Atrioventricular filling' },
          { id: 'ord3', stepNumber: 3, text: 'Right Ventricle ejects through Pulmonary Valve to Pulmonary Trunk', detail: 'Transit to lungs' },
          { id: 'ord4', stepNumber: 4, text: 'Alveolar capillaries re-oxygenate blood; Pulmonary Veins return it to Left Atrium', detail: 'Gas exchange completed' },
          { id: 'ord5', stepNumber: 5, text: 'Blood passes through Mitral Valve into Left Ventricle', detail: 'High-capacity chamber loading' },
          { id: 'ord6', stepNumber: 6, text: 'Left Ventricle powerfully contracts, ejecting blood into Aorta', detail: 'Systemic perfusion initiated' },
        ],
      },
      formulaBuilder: {
        title: 'Assemble the Cardiac Output Formula',
        instructions: 'Drag and arrange the equation components to construct the primary cardiac output formula, then solve the hemodynamics challenge.',
        challenges: [
          {
            id: 'form1',
            name: 'Cardiac Output Equation',
            prompt: 'Construct the equation relating Cardiac Output (CO), Stroke Volume (SV), and Heart Rate (HR).',
            targetSequence: ['CO', '=', 'SV', '×', 'HR'],
            scrambledTokens: [
              { id: 't1', token: 'HR', type: 'variable' },
              { id: 't2', token: '=', type: 'operator' },
              { id: 't3', token: 'CO', type: 'variable' },
              { id: 't4', token: '×', type: 'operator' },
              { id: 't5', token: 'SV', type: 'variable' },
              { id: 't6', token: '+', type: 'operator' },
              { id: 't7', token: 'MAP', type: 'variable' },
            ],
            followUpProblem: {
              question: 'If a patient has a Stroke Volume of 80 mL and a Heart Rate of 70 beats/min, what is the Cardiac Output in Liters/min?',
              variables: { SV: 80, HR: 70 },
              answer: 5.6,
              unit: 'L/min',
            },
          },
        ],
      },
      diagramLabeler: {
        diagramTitle: 'Heart Anatomy Hotspot Mapping',
        diagramType: 'circulatory_system',
        hotspots: [
          { id: 'hs1', label: 'Superior Vena Cava', targetX: 25, targetY: 18, description: 'Large venous vessel returning blood from upper extremities' },
          { id: 'hs2', label: 'Right Atrium', targetX: 28, targetY: 38, description: 'Receives deoxygenated systemic return' },
          { id: 'hs3', label: 'Right Ventricle', targetX: 35, targetY: 66, description: 'Thinner-walled pump sending blood into pulmonary circuit' },
          { id: 'hs4', label: 'Aorta', targetX: 55, targetY: 15, description: 'High-pressure arch distributing oxygenated blood' },
          { id: 'hs5', label: 'Left Atrium', targetX: 70, targetY: 38, description: 'Receives four pulmonary veins from the lungs' },
          { id: 'hs6', label: 'Left Ventricle', targetX: 66, targetY: 68, description: 'Massive muscular chamber generating 120 mmHg systemic pressure' },
        ],
      },
      bossChallenge: {
        bossName: 'Dr. Vance, Chief of Cardiology',
        bossTitle: 'Cardiovascular Dynamics Boss Exam',
        totalHp: 400,
        masteryRewardXp: 350,
        phases: [
          {
            phase: 1,
            title: 'Phase 1: Chamber Anatomy',
            bossDialog: '"Show me you understand the fundamental anatomy of the right versus left heart chambers before we proceed."',
            question: {
              id: 'bq1',
              type: 'multiple_choice',
              difficulty: 'easy',
              prompt: 'Which anatomical structure separates the left and right ventricles to prevent mixing of oxygenated and deoxygenated blood?',
              options: ['Interventricular Septum', 'Fossa Ovalis', 'Ligamentum Arteriosum', 'Chordae Tendineae'],
              correctOptionIndex: 0,
              explanation: 'The muscular interventricular septum provides a continuous anatomical barrier dividing the two ventricular chambers.',
              lectureConceptSource: 'Cardiac Anatomy Overview',
            },
            damageToBoss: 100,
          },
          {
            phase: 2,
            title: 'Phase 2: Valve Mechanics',
            bossDialog: '"Good. Now answer: how do the atrioventricular valves stay closed during peak 120 mmHg ventricular pressure without prolapsing?"',
            question: {
              id: 'bq2',
              type: 'multiple_choice',
              difficulty: 'medium',
              prompt: 'What structures anchor the tricuspid and mitral valve leaflets to the ventricular papillary muscles to prevent valve eversion during systole?',
              options: ['Chordae Tendineae', 'Trabeculae Carneae', 'Pectinate Muscles', 'Crista Terminalis'],
              correctOptionIndex: 0,
              explanation: 'Tendinous cords known as chordae tendineae tether valve cusps to papillary muscles, counteracting high systolic pressures to prevent prolapse.',
              lectureConceptSource: 'Valve Mechanics',
            },
            damageToBoss: 100,
          },
          {
            phase: 3,
            title: 'Phase 3: Hemodynamic Calculations',
            bossDialog: '"Impressive! Let us see if your mathematical calculation holds under clinical pressure!"',
            question: {
              id: 'bq3',
              type: 'multiple_choice',
              difficulty: 'hard',
              prompt: 'A patient presents with acute blood loss. Stroke volume drops to 40 mL/beat. To maintain a resting cardiac output of 4.8 L/min, what compensatory heart rate must the autonomic nervous system elicit?',
              options: ['120 beats/min', '95 beats/min', '80 beats/min', '140 beats/min'],
              correctOptionIndex: 0,
              explanation: 'HR = CO / SV = 4,800 mL/min ÷ 40 mL/beat = 120 beats/min. Tachycardia is the immediate compensatory mechanism for hypovolemia.',
              lectureConceptSource: 'Cardiac Output Regulation',
            },
            damageToBoss: 100,
          },
          {
            phase: 4,
            title: 'Final Phase: Clinical Pathophysiology',
            bossDialog: '"Final question: A patient develops severe aortic stenosis. How will the left ventricular myocardium adapt chronically?"',
            question: {
              id: 'bq4',
              type: 'multiple_choice',
              difficulty: 'hard',
              prompt: 'Chronic outflow tract restriction from aortic valve calcification forces the left ventricle to develop:',
              options: [
                'Concentric Left Ventricular Hypertrophy (thickening of walls to maintain wall stress)',
                'Eccentric dilation with thin atrophied myocardium',
                'Right ventricular failure with zero left ventricular alteration',
                'Permanent dilation of the pulmonary trunk alone',
              ],
              correctOptionIndex: 0,
              explanation: 'According to Laplace\'s law, increased afterload induces concentric hypertrophy—adding sarcomeres in parallel to normalize wall stress.',
              lectureConceptSource: 'Left Ventricular Adaptation',
            },
            damageToBoss: 100,
          },
        ],
      },
    },
  },

  'economics-supply-demand': {
    lecture: {
      id: 'economics-supply-demand',
      title: 'Macroeconomics: Supply, Demand & Market Equilibrium',
      subject: 'Economics',
      summary:
        'An introductory university economics lecture analyzing the mechanics of supply and demand schedules, equilibrium price determination, consumer and producer surplus, price elasticities, and the ripple effects of demand and supply shocks.',
      estimatedDuration: '4 min lesson',
      originalFileName: 'Econ_101_Supply_Demand_Equilibrium.pdf',
      fileSize: '2.1 MB',
      pageCount: 22,
      learningObjectives: [
        'Formulate the Law of Demand and the Law of Supply with their respective graphical slopes.',
        'Calculate market equilibrium price (P*) and equilibrium quantity (Q*).',
        'Analyze market disequilibria: price ceilings leading to shortages and price floors leading to surpluses.',
        'Distinguish between movements along a curve versus shifts of the entire curve.',
      ],
      keyTerms: [
        { term: 'Law of Demand', definition: 'Ceteris paribus, as price rises, quantity demanded falls due to substitution and income effects.' },
        { term: 'Law of Supply', definition: 'Ceteris paribus, as price rises, suppliers produce a higher quantity to capture marginal profit.' },
        { term: 'Market Equilibrium', definition: 'The intersection point (P*, Q*) where Quantity Demanded equals Quantity Supplied with zero shortage or surplus.' },
        { term: 'Price Elasticity of Demand', definition: 'The percentage change in quantity demanded divided by the percentage change in price (%ΔQd / %ΔP).' },
        { term: 'Consumer Surplus', definition: 'The economic benefit gained when a consumer purchases a good for less than the maximum price they were willing to pay.' },
      ],
      formulas: [
        {
          name: 'Price Elasticity of Demand (Ed)',
          formula: 'Ed = (%ΔQd) / (%ΔP)',
          explanation: 'Measures the responsiveness of quantity demanded to a change in the product price.',
          variables: [
            { symbol: 'Ed', label: 'Elasticity of Demand' },
            { symbol: '%ΔQd', label: 'Percentage Change in Quantity Demanded' },
            { symbol: '%ΔP', label: 'Percentage Change in Price' },
          ],
        },
        {
          name: 'Market Equilibrium Condition',
          formula: 'Qd(P*) = Qs(P*)',
          explanation: 'Price where quantity demanded precisely clears quantity supplied.',
          variables: [
            { symbol: 'P*', label: 'Equilibrium Price' },
            { symbol: 'Q*', label: 'Equilibrium Quantity' },
          ],
        },
      ],
      topics: [
        {
          id: 'market-curves',
          title: 'The Supply & Demand Coordinate Plane',
          summary: 'Prices serve as market rationing mechanisms, balancing buyer willingness to pay against seller marginal cost.',
          concepts: [
            {
              id: 'ec1',
              name: 'The Downward-Sloping Demand Curve',
              explanation: 'Represents the inverse relationship between price and quantity demanded by consumers.',
              importantFacts: ['Shifts in demand occur when non-price determinants change: income, preferences, prices of related goods.'],
              terms: ['Demand Schedule', 'Inverse Slope', 'Willingness to Pay'],
              examples: ['A new viral study praises coffee health benefits, shifting coffee demand curve rightward.'],
              visualIdeas: ['Coordinate axes with downward sloping blue line D, moving along curve vs shifting entire line.'],
            },
            {
              id: 'ec2',
              name: 'The Upward-Sloping Supply Curve',
              explanation: 'Reflects higher marginal production costs as output expands, requiring higher market prices to incentivize production.',
              importantFacts: ['Technology improvements shift supply outward/rightward, lowering equilibrium price.'],
              terms: ['Supply Schedule', 'Positive Slope', 'Marginal Cost'],
              examples: ['Automation reduces assembly cost, shifting automotive supply curve rightward.'],
              visualIdeas: ['Upward sloping orange line S intersecting D.'],
            },
          ],
        },
      ],
      createdAt: Date.now(),
    },
    lesson: {
      id: 'lesson-econ-1',
      lectureId: 'economics-supply-demand',
      title: 'Dynamic Coordinate Geometry of Market Equilibrium',
      summary: 'Watch supply and demand curves interact in real time: observe market clearing price, test demand shocks, and visualize surplus and shortages.',
      totalDuration: 180,
      scenes: [
        {
          id: 'scene-econ-1',
          order: 1,
          duration: 40,
          title: 'The Fundamental Supply & Demand Graph',
          narration:
            'In economic analysis, the market coordinate plane places Price on the vertical Y-axis and Quantity on the horizontal X-axis. Notice the downward slope of the blue Demand curve: as prices fall, consumers purchase more. In contrast, the orange Supply curve slopes upward: producers supply more units only when prices rise to cover marginal costs.',
          visualType: 'graph_animation',
          visualDescription:
            'A sharp Cartesian coordinate plane with labeled axes (Price Y, Quantity X). An animated blue downward-sloping line D forms alongside an orange upward-sloping line S. The intersection glows with a pulsing equilibrium marker (P*, Q*).',
          customVisualKey: 'supply_demand',
          elements: [
            { id: 'eg1', type: 'curve', label: 'Demand Curve (D)', x: 30, y: 30, color: '#3b82f6', animation: 'flow' },
            { id: 'eg2', type: 'curve', label: 'Supply Curve (S)', x: 70, y: 70, color: '#f97316', animation: 'flow' },
            { id: 'eg3', type: 'node', label: 'Equilibrium (P*, Q*)', x: 50, y: 50, color: '#10b981', animation: 'pulse' },
          ],
          labels: [
            { text: 'Y-Axis: Price ($)', x: 10, y: 20 },
            { text: 'X-Axis: Quantity (Units)', x: 80, y: 90 },
            { text: 'Equilibrium Point E', x: 52, y: 46, highlight: true },
          ],
          keyTakeaway: 'The intersection of supply and demand clears the market with zero excess demand or supply.',
        },
        {
          id: 'scene-econ-2',
          order: 2,
          duration: 45,
          title: 'The Shock: Rightward Shift in Demand',
          narration:
            'What happens when consumer income rises or a product becomes wildly popular? The entire Demand curve shifts rightward to D-prime. At the old equilibrium price of ten dollars, there is now an immediate shortage: buyers want more than sellers have on hand. Buyers bid up the price until a new, higher equilibrium is established.',
          visualType: 'graph_animation',
          visualDescription:
            'The blue demand curve smoothly shifts rightward from D1 to D2. A red shortage bracket appears temporarily between Qd and Qs, followed by the equilibrium point sliding up along the orange supply curve to a higher P* and higher Q*.',
          customVisualKey: 'supply_demand',
          elements: [
            { id: 'eg4', type: 'curve', label: 'Shift to D2', x: 60, y: 40, color: '#60a5fa', animation: 'shift_curve' },
            { id: 'eg5', type: 'arrow', label: 'Shortage Drives Price Up', x: 50, y: 65, color: '#ef4444', animation: 'flow' },
          ],
          labels: [
            { text: 'Demand Shift Right (D1 → D2)', x: 45, y: 25, highlight: true },
            { text: 'New Higher Price P*2', x: 15, y: 35 },
          ],
          keyTakeaway: 'An increase in demand causes both equilibrium price and equilibrium quantity to rise.',
        },
      ],
    },
    quiz: {
      id: 'quiz-econ-1',
      lectureId: 'economics-supply-demand',
      title: 'Supply, Demand & Market Equilibrium Exam',
      questions: [
        {
          id: 'eq1',
          type: 'multiple_choice',
          difficulty: 'easy',
          prompt: 'What happens to equilibrium price and quantity when consumer demand increases while supply remains constant?',
          options: [
            'Equilibrium price rises and equilibrium quantity rises.',
            'Equilibrium price falls and equilibrium quantity rises.',
            'Equilibrium price rises and equilibrium quantity falls.',
            'Both price and quantity remain unchanged.',
          ],
          correctOptionIndex: 0,
          explanation: 'A rightward shift in demand intersects the unchanged upward-sloping supply curve at a higher price and higher quantity.',
          lectureConceptSource: 'Market Shifts & Equilibrium Dynamics',
        },
        {
          id: 'eq2',
          type: 'multiple_choice',
          difficulty: 'medium',
          prompt: 'If the government imposes a binding price ceiling below the equilibrium price, what is the inevitable economic result?',
          options: [
            'A market shortage (excess demand).',
            'A market surplus (excess supply).',
            'An outward shift in the supply curve.',
            'A decrease in quantity demanded.',
          ],
          correctOptionIndex: 0,
          explanation: 'When price is capped artificially low, quantity demanded exceeds quantity supplied, creating an unresolved shortage.',
          lectureConceptSource: 'Disequilibrium & Price Controls',
        },
      ],
    },
    games: {
      lectureId: 'economics-supply-demand',
      matchConcepts: {
        title: 'Match Economic Mechanisms',
        instructions: 'Match economic terms to their corresponding market behavior.',
        pairs: [
          { id: 'ecm1', term: 'Binding Price Ceiling', definition: 'Legal maximum price set below equilibrium creating shortages' },
          { id: 'ecm2', term: 'Substitute Good', definition: 'A product whose demand rises when another good’s price increases' },
          { id: 'ecm3', term: 'Complement Good', definition: 'A product whose demand falls when another good’s price increases' },
          { id: 'ecm4', term: 'Price Floor', definition: 'Legal minimum price set above equilibrium (e.g. minimum wage)' },
        ],
      },
      memoryMatch: {
        title: 'Economics Concept Match',
        instructions: 'Flip tiles to pair economic definitions.',
        pairs: [
          { id: 'em1', term: 'Shortage', definition: 'Quantity demanded exceeds quantity supplied' },
          { id: 'em2', term: 'Surplus', definition: 'Quantity supplied exceeds quantity demanded' },
          { id: 'em3', term: 'Inelastic Demand', definition: 'Price elasticity magnitude less than 1.0' },
          { id: 'em4', term: 'Ceteris Paribus', definition: 'All other variables held constant' },
        ],
      },
      rapidFire: {
        title: 'Market Shock Rapid Fire',
        instructions: 'Identify curve movements within 10 seconds per round!',
        timePerQuestion: 10,
        questions: [
          {
            id: 'erf1',
            prompt: 'Does a decrease in production costs shift the supply curve left or right?',
            options: ['Rightward (Increase in Supply)', 'Leftward (Decrease in Supply)', 'Upward along Demand', 'No shift'],
            correctIndex: 0,
            concept: 'Supply curve shifts',
          },
          {
            id: 'erf2',
            prompt: 'What happens to demand for normal goods when consumer income falls?',
            options: ['Demand curve shifts left', 'Demand curve shifts right', 'Supply shifts right', 'Price rises'],
            correctIndex: 0,
            concept: 'Income effect on normal goods',
          },
        ],
      },
      sortIt: {
        title: 'Determinants of Demand vs Supply',
        instructions: 'Sort market drivers into Demand Shifters or Supply Shifters.',
        categories: [
          { id: 'det-dem', name: 'Demand Shifter', description: 'Changes consumer willingness to pay' },
          { id: 'det-sup', name: 'Supply Shifter', description: 'Changes producer marginal costs' },
        ],
        items: [
          { id: 'esi1', text: 'Consumer Tastes & Advertising', categoryId: 'det-dem' },
          { id: 'esi2', text: 'Raw Material & Input Costs', categoryId: 'det-sup' },
          { id: 'esi3', text: 'Number of Buyers in Market', categoryId: 'det-dem' },
          { id: 'esi4', text: 'Manufacturing Technology & Automation', categoryId: 'det-sup' },
          { id: 'esi5', text: 'Subsidies or Taxes on Producers', categoryId: 'det-sup' },
          { id: 'esi6', text: 'Expectations of Future Buyer Income', categoryId: 'det-dem' },
        ],
      },
      putItInOrder: {
        title: 'Market Equilibrium Adjustment Sequence',
        instructions: 'Order the steps when a sudden positive demand shock hits an equilibrium market.',
        processName: 'Price Adjustment to New Equilibrium',
        items: [
          { id: 'eord1', stepNumber: 1, text: 'Initial state: Market clears at price P*1 with Q*1', detail: 'Zero shortage' },
          { id: 'eord2', stepNumber: 2, text: 'Exogenous shock causes Demand curve to shift rightward to D2', detail: 'Buyers seek more' },
          { id: 'eord3', stepNumber: 3, text: 'At old price P*1, Quantity Demanded exceeds Quantity Supplied', detail: 'Shortage emerges' },
          { id: 'eord4', stepNumber: 4, text: 'Inventories deplete; buyers bid up prices and sellers raise quotes', detail: 'Price rationing' },
          { id: 'eord5', stepNumber: 5, text: 'Higher price incentivizes suppliers to move up supply curve', detail: 'Expanded production' },
          { id: 'eord6', stepNumber: 6, text: 'New equilibrium established at higher P*2 and higher Q*2', detail: 'Market cleared again' },
        ],
      },
      formulaBuilder: {
        title: 'Price Elasticity of Demand Formula',
        instructions: 'Assemble the formula for calculating Price Elasticity of Demand.',
        challenges: [
          {
            id: 'eform1',
            name: 'Price Elasticity Formula',
            prompt: 'Construct the definition of Price Elasticity of Demand (Ed = %ΔQd / %ΔP).',
            targetSequence: ['Ed', '=', '%ΔQd', '/', '%ΔP'],
            scrambledTokens: [
              { id: 'et1', token: '%ΔP', type: 'variable' },
              { id: 'et2', token: '=', type: 'operator' },
              { id: 'et3', token: '/', type: 'operator' },
              { id: 'et4', token: 'Ed', type: 'variable' },
              { id: 'et5', token: '%ΔQd', type: 'variable' },
            ],
            followUpProblem: {
              question: 'If price drops by 10% and quantity demanded increases by 20%, what is the elasticity of demand magnitude?',
              variables: { pctQ: 20, pctP: 10 },
              answer: 2.0,
              unit: '(Elastic)',
            },
          },
        ],
      },
      diagramLabeler: {
        diagramTitle: 'Market Graph Anatomy',
        diagramType: 'market_graph',
        hotspots: [
          { id: 'ehs1', label: 'Price (Y-Axis)', targetX: 12, targetY: 15, description: 'Vertical axis showing dollar price' },
          { id: 'ehs2', label: 'Quantity (X-Axis)', targetX: 85, targetY: 88, description: 'Horizontal axis showing units produced/consumed' },
          { id: 'ehs3', label: 'Demand Curve', targetX: 30, targetY: 30, description: 'Downward sloping curve reflecting willingness to pay' },
          { id: 'ehs4', label: 'Supply Curve', targetX: 30, targetY: 70, description: 'Upward sloping curve reflecting producer costs' },
          { id: 'ehs5', label: 'Equilibrium (P*, Q*)', targetX: 50, targetY: 50, description: 'Intersection point where market clears' },
        ],
      },
      bossChallenge: {
        bossName: 'Professor Sterling, Chief Economist',
        bossTitle: 'Market Dynamics Boss Challenge',
        totalHp: 300,
        masteryRewardXp: 300,
        phases: [
          {
            phase: 1,
            title: 'Phase 1: Equilibrium Foundations',
            bossDialog: '"Explain how market forces eliminate a temporary surplus without government intervention!"',
            question: {
              id: 'ebq1',
              type: 'multiple_choice',
              difficulty: 'medium',
              prompt: 'When price is set above equilibrium, what market mechanism restores equilibrium?',
              options: [
                'Sellers lower prices to sell unsold excess inventory, decreasing quantity supplied and increasing quantity demanded.',
                'The government forces consumers to purchase surplus items.',
                'Suppliers permanently destroy the supply curve.',
                'Demand shifts leftward automatically.',
              ],
              correctOptionIndex: 0,
              explanation: 'Unsold inventory forces competitive price discounts until market clears at P*.',
              lectureConceptSource: 'Market Equilibrium Dynamics',
            },
            damageToBoss: 100,
          },
          {
            phase: 2,
            title: 'Phase 2: Simultaneous Shocks',
            bossDialog: '"Now solve this university exam puzzle: What happens if demand rises AND supply falls simultaneously?"',
            question: {
              id: 'ebq2',
              type: 'multiple_choice',
              difficulty: 'hard',
              prompt: 'If demand increases (shifts right) AND supply decreases (shifts left) simultaneously:',
              options: [
                'Equilibrium price definitely rises, but equilibrium quantity is indeterminate.',
                'Equilibrium quantity definitely rises, but price is indeterminate.',
                'Both price and quantity must fall.',
                'Both price and quantity remain identical.',
              ],
              correctOptionIndex: 0,
              explanation: 'Both shifts exert upward pressure on price, guaranteeing P* rises. However, demand increases Q while supply decreases Q, making Q* dependent on which shift is larger.',
              lectureConceptSource: 'Simultaneous Market Shifts',
            },
            damageToBoss: 100,
          },
          {
            phase: 3,
            title: 'Final Phase: Deadweight Loss',
            bossDialog: '"Final challenge: If a price ceiling creates a shortage, what happens to total economic surplus?"',
            question: {
              id: 'ebq3',
              type: 'multiple_choice',
              difficulty: 'hard',
              prompt: 'A binding price ceiling leads to deadweight loss because:',
              options: [
                'Mutually beneficial trades between willing buyers and sellers are prevented from occurring below Q*.',
                'Suppliers receive infinite monopoly profits.',
                'Consumer surplus exceeds total GDP.',
                'The demand curve becomes vertical.',
              ],
              correctOptionIndex: 0,
              explanation: 'Deadweight loss represents foregone surplus from transactions that do not take place because output is restricted.',
              lectureConceptSource: 'Deadweight Loss & Welfare Economics',
            },
            damageToBoss: 100,
          },
        ],
      },
    },
  },

  'physics-newton-dynamics': {
    lecture: {
      id: 'physics-newton-dynamics',
      title: 'Physics: Newton\'s Laws & Classical Dynamics',
      subject: 'Physics',
      summary:
        'A university mechanics lecture examining Newton\'s Three Laws of Motion, vector force resolution, free-body diagrams, static versus kinetic friction, and dynamic momentum conservation.',
      estimatedDuration: '4 min lesson',
      originalFileName: 'Physics_201_Classical_Mechanics.pdf',
      fileSize: '4.1 MB',
      pageCount: 32,
      learningObjectives: [
        'Formulate Newton’s Second Law vectorially as ΣF = ma.',
        'Deconstruct forces into orthogonal components using Free-Body Diagrams (FBD).',
        'Differentiate between static friction coefficient (μs) and kinetic friction coefficient (μk).',
        'Demonstrate action-reaction pairs according to Newton’s Third Law.',
      ],
      keyTerms: [
        { term: 'Inertia', definition: 'The tendency of an object to resist changes in its state of motion, directly proportional to its mass.' },
        { term: 'Net Force (ΣF)', definition: 'The vector sum of all external forces acting simultaneously on a body.' },
        { term: 'Normal Force (Fn)', definition: 'The perpendicular contact force exerted by a supporting surface against an object resting on it.' },
        { term: 'Kinetic Friction (fk)', definition: 'The resistive contact force opposing motion between sliding surfaces, calculated as fk = μk × Fn.' },
      ],
      formulas: [
        {
          name: 'Newton\'s Second Law',
          formula: 'ΣF = m × a',
          explanation: 'Net force equals mass times acceleration in the direction of the net force vector.',
          variables: [
            { symbol: 'ΣF', label: 'Net Force Vector (Newtons, N)' },
            { symbol: 'm', label: 'Mass (kg)' },
            { symbol: 'a', label: 'Acceleration (m/s²)' },
          ],
        },
        {
          name: 'Friction Force Law',
          formula: 'fk = μk × Fn',
          explanation: 'Kinetic frictional force opposing sliding motion.',
          variables: [
            { symbol: 'fk', label: 'Kinetic Friction Force (N)' },
            { symbol: 'μk', label: 'Kinetic Friction Coefficient' },
            { symbol: 'Fn', label: 'Normal Force (N)' },
          ],
        },
      ],
      topics: [
        {
          id: 'newton-laws',
          title: 'The Three Pillars of Newtonian Mechanics',
          summary: 'Force governs acceleration, not velocity. Mass acts as universal resistance to acceleration.',
          concepts: [
            {
              id: 'pc1',
              name: 'Second Law Vector Dynamics',
              explanation: 'Acceleration is directly proportional to net force and inversely proportional to body mass.',
              importantFacts: ['If ΣF = 0, acceleration is strictly zero (First Law is a special case of the Second Law).'],
              terms: ['Vector Sum', 'Acceleration', 'Net Force'],
              examples: ['Doubling engine thrust doubles rocket acceleration if mass is constant.'],
              visualIdeas: ['Box on surface with force arrow F pulling right, friction arrow f pointing left, acceleration gauge showing m/s².'],
            },
          ],
        },
      ],
      createdAt: Date.now(),
    },
    lesson: {
      id: 'lesson-phys-1',
      lectureId: 'physics-newton-dynamics',
      title: 'Newtonian Force Vectors in Real-Time Motion',
      summary: 'Watch mass respond to vector forces: adjust applied force, observe opposing friction, and watch acceleration scale exactly with F=ma.',
      totalDuration: 180,
      scenes: [
        {
          id: 'scene-phys-1',
          order: 1,
          duration: 45,
          title: 'Forces in Action: Net Force & Acceleration',
          narration:
            'Observe this five-kilogram mass resting on a horizontal plane. When an applied force pushes it to the right, a resistive frictional force opposes it to the left. The actual acceleration depends not on either single force, but strictly on the Net Force vector—the sum of all external vectors.',
          visualType: 'physics_simulation',
          visualDescription:
            'A metallic block resting on a textured plane. An applied force vector arrow F_app pulls rightward in vibrant green, a friction arrow f_k opposes leftward in crimson, and a live vector subtraction equation shows F_net = F_app - f_k accelerating the block.',
          customVisualKey: 'newton_dynamics',
          elements: [
            { id: 'pe1', type: 'box', label: 'Mass m = 5 kg', x: 45, y: 60, color: '#6366f1', animation: 'flow' },
            { id: 'pe2', type: 'arrow', label: 'F_app = 30 N →', x: 65, y: 60, color: '#10b981', animation: 'flow', direction: 'right' },
            { id: 'pe3', type: 'arrow', label: '← f_k = 10 N', x: 25, y: 60, color: '#ef4444', animation: 'flow', direction: 'left' },
            { id: 'pe4', type: 'formula', label: 'a = F_net / m = 4 m/s²', x: 50, y: 25, color: '#fbbf24', animation: 'pulse' },
          ],
          labels: [
            { text: 'Net Force = 20 N Right', x: 50, y: 35, highlight: true },
            { text: 'Mass m = 5 kg', x: 45, y: 72 },
          ],
          keyTakeaway: 'Acceleration is directly proportional to net force and inversely proportional to inertia (mass).',
        },
      ],
    },
    quiz: {
      id: 'quiz-phys-1',
      lectureId: 'physics-newton-dynamics',
      title: 'Newtonian Classical Dynamics Exam',
      questions: [
        {
          id: 'pq1',
          type: 'multiple_choice',
          difficulty: 'medium',
          prompt: 'A 10 kg block is pushed across a horizontal surface by a 50 N forward force. A constant friction force of 20 N opposes motion. What is the block\'s acceleration?',
          options: ['3.0 m/s²', '5.0 m/s²', '2.0 m/s²', '7.0 m/s²'],
          correctOptionIndex: 0,
          explanation: 'Net Force = 50 N - 20 N = 30 N forward. a = F_net / m = 30 N ÷ 10 kg = 3.0 m/s².',
          lectureConceptSource: 'Newton’s Second Law Vector Formulation',
        },
      ],
    },
    games: {
      lectureId: 'physics-newton-dynamics',
      matchConcepts: {
        title: 'Match Mechanics Principles',
        instructions: 'Match each physics principle with its definition.',
        pairs: [
          { id: 'pmp1', term: 'First Law (Inertia)', definition: 'Objects remain in uniform motion unless acted upon by a non-zero net force' },
          { id: 'pmp2', term: 'Second Law', definition: 'Net force equals the time rate of change of momentum (F = ma)' },
          { id: 'pmp3', term: 'Third Law', definition: 'For every action force, there is an equal and opposite reaction force' },
          { id: 'pmp4', term: 'Static Friction', definition: 'Opposes the initiation of relative motion between stationary surfaces' },
        ],
      },
      memoryMatch: {
        title: 'Physics Equation Memory Grid',
        instructions: 'Pair physics variables and units.',
        pairs: [
          { id: 'pm1', term: 'Force', definition: 'Newtons (kg·m/s²)' },
          { id: 'pm2', term: 'Mass', definition: 'Kilograms (kg)' },
          { id: 'pm3', term: 'Acceleration', definition: 'm/s²' },
          { id: 'pm4', term: 'Friction Coefficient', definition: 'Dimensionless ratio (μ)' },
        ],
      },
      rapidFire: {
        title: 'Mechanics Rapid Fire',
        instructions: 'Answer within 10 seconds per problem!',
        timePerQuestion: 10,
        questions: [
          {
            id: 'prf1',
            prompt: 'If you double the net force on an object, its acceleration:',
            options: ['Doubles', 'Halves', 'Quadruples', 'Remains unchanged'],
            correctIndex: 0,
            concept: 'Newton 2nd Law proportion',
          },
        ],
      },
      sortIt: {
        title: 'Contact Forces vs Field Forces',
        instructions: 'Sort each force into Contact or Non-Contact Field force.',
        categories: [
          { id: 'pcat-cont', name: 'Contact Force', description: 'Requires physical touching' },
          { id: 'pcat-field', name: 'Field Force', description: 'Acts over distance via physical fields' },
        ],
        items: [
          { id: 'psi1', text: 'Normal Force from Floor', categoryId: 'pcat-cont' },
          { id: 'psi2', text: 'Gravitational Attraction', categoryId: 'pcat-field' },
          { id: 'psi3', text: 'Kinetic Friction Force', categoryId: 'pcat-cont' },
          { id: 'psi4', text: 'Electrostatic Coulomb Force', categoryId: 'pcat-field' },
          { id: 'psi5', text: 'Tension in a Rope', categoryId: 'pcat-cont' },
          { id: 'psi6', text: 'Magnetic Attraction', categoryId: 'pcat-field' },
        ],
      },
      putItInOrder: {
        title: 'Solving Free-Body Diagram Problems',
        instructions: 'Arrange the standard engineering procedure for dynamics analysis.',
        processName: 'Classical Dynamics Solution Protocol',
        items: [
          { id: 'pord1', stepNumber: 1, text: 'Isolate the body of interest and choose a coordinate system', detail: 'Step 1' },
          { id: 'pord2', stepNumber: 2, text: 'Draw all external contact and field forces as vector arrows', detail: 'Step 2' },
          { id: 'pord3', stepNumber: 3, text: 'Decompose oblique force vectors into X and Y orthogonal components', detail: 'Step 3' },
          { id: 'pord4', stepNumber: 4, text: 'Apply ΣFx = m·ax and ΣFy = m·ay equations', detail: 'Step 4' },
          { id: 'pord5', stepNumber: 5, text: 'Solve the algebraic equations for unknown acceleration or tension', detail: 'Step 5' },
        ],
      },
      formulaBuilder: {
        title: 'Build Newton\'s Second Law',
        instructions: 'Assemble F = m × a and solve for acceleration.',
        challenges: [
          {
            id: 'pform1',
            name: 'Newton\'s Second Law',
            prompt: 'Construct the equation for net force: F = m × a',
            targetSequence: ['F', '=', 'm', '×', 'a'],
            scrambledTokens: [
              { id: 'pt1', token: 'a', type: 'variable' },
              { id: 'pt2', token: '=', type: 'operator' },
              { id: 'pt3', token: 'F', type: 'variable' },
              { id: 'pt4', token: '×', type: 'operator' },
              { id: 'pt5', token: 'm', type: 'variable' },
            ],
            followUpProblem: {
              question: 'If a 4 kg object experiences a net force of 24 N, what is its acceleration in m/s²?',
              variables: { F: 24, m: 4 },
              answer: 6.0,
              unit: 'm/s²',
            },
          },
        ],
      },
      bossChallenge: {
        bossName: 'Sir Isaac, Grand Master of Dynamics',
        bossTitle: 'Classical Mechanics Boss Exam',
        totalHp: 300,
        masteryRewardXp: 300,
        phases: [
          {
            phase: 1,
            title: 'Phase 1: Action-Reaction Paradox',
            bossDialog: '"If a horse pulls a cart, and the cart pulls backward on the horse with equal force, why does the cart move forward?"',
            question: {
              id: 'pbq1',
              type: 'multiple_choice',
              difficulty: 'medium',
              prompt: 'Why does the cart accelerate forward despite Newton’s Third Law equal and opposite reaction?',
              options: [
                'Action and reaction forces act on different objects; the horse pushes backward against the ground, and the ground pushes forward on the horse with net forward force.',
                'The horse pulls slightly before the cart reacts.',
                'Newton’s third law only applies to stationary bodies.',
                'Friction between the cart and horse cancels the reaction.',
              ],
              correctOptionIndex: 0,
              explanation: 'Third law forces never cancel each other because they act on separate bodies. The horse-cart system moves because the forward force of the ground on the horse exceeds the rolling friction on the cart.',
              lectureConceptSource: 'Newton’s Third Law',
            },
            damageToBoss: 150,
          },
          {
            phase: 2,
            title: 'Phase 2: Apparent Weightlessness',
            bossDialog: '"Final test: What does a bathroom scale read inside an elevator whose cable snaps into free fall?"',
            question: {
              id: 'pbq2',
              type: 'multiple_choice',
              difficulty: 'hard',
              prompt: 'In a freely falling elevator accelerating downward at g = 9.8 m/s², a passenger’s apparent weight (normal force) is:',
              options: ['0 Newtons (apparent weightlessness)', 'Equal to true weight mg', 'Double the true weight', 'Half the true weight'],
              correctOptionIndex: 0,
              explanation: 'Fn - mg = m(-g) => Fn = 0. Without normal force from the floor, apparent weight is zero.',
              lectureConceptSource: 'Elevator Dynamics & Normal Force',
            },
            damageToBoss: 150,
          },
        ],
      },
    },
  },
};
